### ISSUE TITLE
Something about stack traces breaks the crap out of 'Create Issue

### ISSUE THREAD

**Issue by rtyler** [rtyler/Hubboard#78]

**Comment by rtyler** [comment]
For example:

```
-> % ./bin/blimpy destroy
/home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:63:in `block in destroy': undefined method `destroy' for nil:NilClass (NoMethodError)
        from /home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:61:in `each'
        from /home/tyler/source/github/gems/blimpy/lib/blimpy/fleet.rb:61:in `destroy'
        from ./bin/blimpy:63:in `destroy'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
        from /home/tyler/.rvm/gems/ruby-1.9.2-p290@blimpy/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from ./bin/blimpy:86:in `<main>'
```

**Comment by rtyler** [comment]
Starting work on this now.

(_This message brought to you by [Hub board](http://hubboard.herokuapp.com/about)_)

**Comment by rtyler** [comment]
I have a hunch that this has to deal with the content type being sent across the wire to Rack. If the content type isn't specifically "text/json" then the Rack form handling middleware will puke

**Comment by rtyler** [comment]
Yep, it seems the content type header on the request is `Content-Type:application/x-www-form-urlencoded`
